spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true

vipps:
  mobilepay:
    api:
      url: https://api.vippsmobilepay.com
    client:
      id: your-client-id
      secret: your-client-secret
    merchant:
      serial: your-merchant-serial
    ocp:
      apimKey: your-ocp-apimkey
    vipps:
      systemName: your-vipps-system-name
      systemVersion: your-vipps-system-version
      systemPlugin: your-vipps-system-plugin
      systemPluginVer: your-vipps-system-plugin-version

server:
  port: 8080